FROM us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101315.3-rc.1

RUN apk add --no-cache jq

COPY entrypoint-l2.sh /entrypoint.sh

VOLUME ["/db"]

ENTRYPOINT ["/bin/sh", "/entrypoint.sh"]
